### ISSUE TITLE
Player lacks permission to update MeasuredTemplate in parent Scene

### ISSUE THREAD

**Issue by Koalahund** [EndlesNights/template-wall-collision#1]
Foundry version: 0.8.6
Gamesystem: PF1 0.78.8
Active Modules: Template Wall Collision, libWrapper, Find the culprit

Problem: Placing a template onto a scene gives players the "User xxx lacks permission to update MeasuredTemplate[xxx] in parent Scene [xxx]" error. Working without the module.

Screenshot:
![LacksPermission](https://user-images.githubusercontent.com/85458282/121559595-01e86c80-ca17-11eb-9630-71816cf28e96.png)

Console error screenshot:
![ConsoleLacksPermission](https://user-images.githubusercontent.com/85458282/121559710-1f1d3b00-ca17-11eb-9620-7ce857cb33aa.png)

**Comment by EndlesNights** [comment]
It appears there was change in how user ID permission checking was done that I didn't catch. Issue should be fixed for 1.0.3
